version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - '8000:3000'
    environment:
      TOKEN_KEY: 'envkey'
  users:
    build: ./users-api
    ports:
      - '8080:3000'
    environment:
      MONGODB_CONNECTION_URI: 'mongodb+srv://mbraer:wk4nFupsbntPbB3l@cluster0.ntrwp.mongodb.net/users?retryWrites=true&w=majority'
      AUTH_API_ADDRESS: 'auth:3000'
  tasks:
    build: ./tasks-api
    ports:
      - '3000:3000'
    environment:
      MONGODB_CONNECTION_URI: 'mongodb+srv://mbraer:wk4nFupsbntPbB3l@cluster0.ntrwp.mongodb.net/users?retryWrites=true&w=majority'
      AUTH_API_ADDRESS: 'auth:3000'