version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '80:80'
    volumes:
      - ./server:/server
      - /server/node_modules
    env_file:
      - ./env/server.env
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/client/src
    stdin_open: true
    tty: true
    depends_on:
      - server
